In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import seaborn as sns
import numpy as np
from datetime import datetime, timedelta
from scipy.stats import pearsonr
from scipy.stats import linregress
from scipy.stats import zscore

## Load and prepare data

In [7]:
# load data
spei_df = pd.read_csv('/home/h99g576/zambia/final/Data/Growing_Period/district_province_spei_growingperiod.csv')

# rename season_year column for compatability with forest loss
spei_df = spei_df.rename(columns={'season_year': 'year', 'mean_growing_spei': 'mean_spei', 'median_growing_spei': 'median_spei'})

# load forest loss data
forest_df = pd.read_csv('/home/h99g576/zambia/final/Data/Forest_Cover_Loss/district_forest_cover.csv')
forest_df['year'] = forest_df['year'].astype(int)

# merge SPEI and forest data
merged_df = pd.merge(spei_df, forest_df, on=['district', 'year'])

In [8]:
# generate lags
for lag in range(1, 6):
    merged_df[f'mean_spei_lag{lag}'] = merged_df.groupby('district')['mean_spei'].shift(lag)

plot_df = merged_df.copy()

# get unique provinces
provinces = plot_df['province'].unique()

def compute_lag_corrs(group):
    results = {}
    for lag in range(0, 6):
        col = f'mean_spei_lag{lag}'
        y_col = 'percent_loss_annual'
        if col in group:
            # drop NaNs
            valid = group[[col, y_col]].dropna()
            if len(valid) >= 3:
                slope, intercept, r_value, p_value, std_err = linregress(valid[col], valid[y_col])
                results[f'corr_lag{lag}'] = r_value
                results[f'pval_lag{lag}'] = p_value
                results[f'slope_lag{lag}'] = slope
                results[f'r2_lag{lag}'] = r_value ** 2
            else:
                results[f'corr_lag{lag}'] = None
                results[f'pval_lag{lag}'] = None
                results[f'slope_lag{lag}'] = None
                results[f'r2_lag{lag}'] = None

        else:
            results[f'corr_lag{lag}'] = None
            results[f'pval_lag{lag}'] = None
            results[f'slope_lag{lag}'] = None
            results[f'r2_lag{lag}'] = None
            
    return pd.Series(results)

plot_df['mean_spei_lag1'] = plot_df.groupby('district')['mean_spei'].shift(0)
plot_df['mean_spei_lag1'] = plot_df.groupby('district')['mean_spei'].shift(1)
plot_df['mean_spei_lag2'] = plot_df.groupby('district')['mean_spei'].shift(2)
plot_df['mean_spei_lag3'] = plot_df.groupby('district')['mean_spei'].shift(3)
plot_df['mean_spei_lag4'] = plot_df.groupby('district')['mean_spei'].shift(4)
plot_df['mean_spei_lag5'] = plot_df.groupby('district')['mean_spei'].shift(5)

multi_lag_corrs = (
    plot_df.groupby('district')[['mean_spei_lag1', 'mean_spei_lag2', 'mean_spei_lag3', 'mean_spei_lag4', 'mean_spei_lag5', 'percent_loss_annual']]
    .apply(compute_lag_corrs)
    .reset_index()
)

# Filter and print significant correlations for each lag
for lag in range(1, 6):
    corr_col = f'corr_lag{lag}'
    pval_col = f'pval_lag{lag}'
    slope_col = f'slope_lag{lag}'
    r2_col = f'r2_lag{lag}'
    
    significant = multi_lag_corrs[multi_lag_corrs[pval_col] < 0.05][['district', corr_col, pval_col, slope_col, r2_col]]
    
    print(f'\nSignificant correlations for Lag {lag} (p < 0.05):')
    print(significant.sort_values(by=corr_col, ascending=False).to_string(index=False))

Significant correlations for Lag 1 (p < 0.05):
district  corr_lag1  pval_lag1  slope_lag1  r2_lag1
Mpulungu   0.623123   0.003335    0.137493 0.388282
   Mbala   0.596150   0.005535    0.312775 0.355395
   Isoka   0.504332   0.023355    0.121074 0.254351
  Mumbwa  -0.477880   0.033082   -0.304023 0.228370

Significant correlations for Lag 2 (p < 0.05):
district  corr_lag2  pval_lag2  slope_lag2  r2_lag2
Mpulungu   0.564731   0.011763    0.153512 0.318922
 Serenje  -0.465627   0.044524   -0.128188 0.216809
  Mwense  -0.504103   0.027752   -0.410085 0.254120
 Chavuma  -0.517097   0.023378   -0.529901 0.267389
   Mansa  -0.536065   0.017988   -0.509601 0.287366

Significant correlations for Lag 3 (p < 0.05):
district  corr_lag3  pval_lag3  slope_lag3  r2_lag3
 Serenje  -0.508148   0.031310   -0.135842 0.258214
 Chavuma  -0.521907   0.026310   -0.521685 0.272387
Chingola  -0.525405   0.025144   -0.493602 0.276050

Significant correlations for Lag 4 (p < 0.05):
     district  corr_lag4  pval_lag4  slope_lag4  r2_lag4
        Mansa  -0.500715   0.040635   -0.451008 0.250715
Chililabombwe  -0.522337   0.031478   -0.746658 0.272836
       Kalomo  -0.523223   0.031140   -0.154167 0.273763
       Mwense  -0.530426   0.028494   -0.408045 0.281352
      Luwingu  -0.545175   0.023619   -0.256669 0.297216
     Chingola  -0.652426   0.004530   -0.589655 0.425659
     Chinsali  -0.656890   0.004173   -0.303148 0.431505

Significant correlations for Lag 5 (p < 0.05):
     district  corr_lag5  pval_lag5  slope_lag5  r2_lag5
   Lufwanyama  -0.508368   0.044357   -0.319806 0.258438
      Senanga  -0.526704   0.036069   -0.183041 0.277417
       Kasama  -0.557806   0.024754   -0.274309 0.311148
     Chingola  -0.577668   0.019106   -0.516645 0.333701
     Chinsali  -0.606120   0.012816   -0.269844 0.367382
      Namwala  -0.649153   0.006508   -0.671710 0.421400
Chililabombwe  -0.669166   0.004584   -0.961759 0.447783
       Kalomo  -0.672218   0.004336   -0.190572 0.451878

In [4]:
plot_df.head()

,district,year,mean_spei,median_spei,n_months,province,province_avg_start_date,province_avg_end_date,forest_cover_ha,loss_m2,percent_loss_annual,mean_spei_lag1,mean_spei_lag2,mean_spei_lag3,mean_spei_lag4,mean_spei_lag5
0,Chadiza,2001,0.364988,0.311898,5,Eastern,November 26,May 04,57181.013721,5.136993e+05,0.089757,NaN,NaN,NaN,NaN,NaN
1,Chadiza,2002,0.281255,0.244052,6,Eastern,November 26,May 04,57127.207503,5.380622e+05,0.094098,0.364988,NaN,NaN,NaN,NaN
2,Chadiza,2003,0.227219,0.217295,5,Eastern,November 26,May 04,56960.977318,1.662302e+06,0.290983,0.281255,0.364988,NaN,NaN,NaN
3,Chadiza,2004,-0.079997,0.072081,7,Eastern,November 26,May 04,56773.795452,1.871819e+06,0.328614,0.227219,0.281255,0.364988,NaN,NaN
4,Chadiza,2005,-0.699067,-0.777293,4,Eastern,November 26,May 04,56703.324923,7.047053e+05,0.124125,-0.079997,0.227219,0.281255,0.364988,NaN

In [9]:
def compute_lag_corrs(group):
    results = {}
    for lag in range(1, 6):
        col = f'mean_spei_lag{lag}'
        y_col = 'percent_loss_annual'
        if col in group:
            # drop NaNs
            valid = group[[col, y_col]].dropna()
            if len(valid) >= 3:
                slope, intercept, r_value, p_value, std_err = linregress(valid[col], valid[y_col])
                results[f'corr_lag{lag}'] = r_value
                results[f'pval_lag{lag}'] = p_value
                results[f'slope_lag{lag}'] = slope
                results[f'r2_lag{lag}'] = r_value ** 2
            else:
                results[f'corr_lag{lag}'] = None
                results[f'pval_lag{lag}'] = None
                results[f'slope_lag{lag}'] = None
                results[f'r2_lag{lag}'] = None

        else:
            results[f'corr_lag{lag}'] = None
            results[f'pval_lag{lag}'] = None
            results[f'slope_lag{lag}'] = None
            results[f'r2_lag{lag}'] = None
            
    return pd.Series(results)

plot_df['mean_spei_lag1'] = plot_df.groupby('district')['mean_spei'].shift(1)
plot_df['mean_spei_lag2'] = plot_df.groupby('district')['mean_spei'].shift(2)
plot_df['mean_spei_lag3'] = plot_df.groupby('district')['mean_spei'].shift(3)
plot_df['mean_spei_lag4'] = plot_df.groupby('district')['mean_spei'].shift(4)
plot_df['mean_spei_lag5'] = plot_df.groupby('district')['mean_spei'].shift(5)

multi_lag_corrs = (
    plot_df.groupby('district')[['mean_spei_lag1', 'mean_spei_lag2', 'mean_spei_lag3', 'mean_spei_lag4', 'mean_spei_lag5', 'percent_loss_annual']]
    .apply(compute_lag_corrs)
    .reset_index()
)

# Filter and print significant correlations for each lag
for lag in range(1, 6):
    corr_col = f'corr_lag{lag}'
    pval_col = f'pval_lag{lag}'
    slope_col = f'slope_lag{lag}'
    r2_col = f'r2_lag{lag}'
    
    significant = multi_lag_corrs[multi_lag_corrs[pval_col] < 0.05][['district', corr_col, pval_col, slope_col, r2_col]]
    
    print(f'\nSignificant correlations for Lag {lag} (p < 0.05):')
    print(significant.sort_values(by=corr_col, ascending=False).to_string(index=False))

Significant correlations for Lag 1 (p < 0.05):
district  corr_lag1  pval_lag1  slope_lag1  r2_lag1
Mpulungu   0.623123   0.003335    0.137493 0.388282
   Mbala   0.596150   0.005535    0.312775 0.355395
   Isoka   0.504332   0.023355    0.121074 0.254351
  Mumbwa  -0.477880   0.033082   -0.304023 0.228370

Significant correlations for Lag 2 (p < 0.05):
district  corr_lag2  pval_lag2  slope_lag2  r2_lag2
Mpulungu   0.564731   0.011763    0.153512 0.318922
 Serenje  -0.465627   0.044524   -0.128188 0.216809
  Mwense  -0.504103   0.027752   -0.410085 0.254120
 Chavuma  -0.517097   0.023378   -0.529901 0.267389
   Mansa  -0.536065   0.017988   -0.509601 0.287366

Significant correlations for Lag 3 (p < 0.05):
district  corr_lag3  pval_lag3  slope_lag3  r2_lag3
 Serenje  -0.508148   0.031310   -0.135842 0.258214
 Chavuma  -0.521907   0.026310   -0.521685 0.272387
Chingola  -0.525405   0.025144   -0.493602 0.276050

Significant correlations for Lag 4 (p < 0.05):
     district  corr_lag4  pval_lag4  slope_lag4  r2_lag4
        Mansa  -0.500715   0.040635   -0.451008 0.250715
Chililabombwe  -0.522337   0.031478   -0.746658 0.272836
       Kalomo  -0.523223   0.031140   -0.154167 0.273763
       Mwense  -0.530426   0.028494   -0.408045 0.281352
      Luwingu  -0.545175   0.023619   -0.256669 0.297216
     Chingola  -0.652426   0.004530   -0.589655 0.425659
     Chinsali  -0.656890   0.004173   -0.303148 0.431505

Significant correlations for Lag 5 (p < 0.05):
     district  corr_lag5  pval_lag5  slope_lag5  r2_lag5
   Lufwanyama  -0.508368   0.044357   -0.319806 0.258438
      Senanga  -0.526704   0.036069   -0.183041 0.277417
       Kasama  -0.557806   0.024754   -0.274309 0.311148
     Chingola  -0.577668   0.019106   -0.516645 0.333701
     Chinsali  -0.606120   0.012816   -0.269844 0.367382
      Namwala  -0.649153   0.006508   -0.671710 0.421400
Chililabombwe  -0.669166   0.004584   -0.961759 0.447783
       Kalomo  -0.672218   0.004336   -0.190572 0.451878

In [10]:
for lag in range(1, 6):
    col = f'mean_spei_lag{lag}'
    z_col = f'z_spei_lag{lag}'
    plot_df[z_col] = (
        plot_df.groupby('district')[col]
        .transform(lambda x: (x - x.mean()) / x.std())
    )

plot_df.head()

,Unnamed: 0.1,Unnamed: 0,district,year,mean_spei,median_spei,n_months,province,forest_cover_ha,loss_m2,...,mean_spei_lag1,mean_spei_lag2,mean_spei_lag3,mean_spei_lag4,mean_spei_lag5,z_spei_lag1,z_spei_lag2,z_spei_lag3,z_spei_lag4,z_spei_lag5
0,1,1,Chadiza,2001,0.353488,0.303945,6,Eastern,57181.013721,5.136993e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,Chadiza,2002,0.281255,0.244052,6,Eastern,57127.207503,5.380622e+05,...,0.353488,NaN,NaN,NaN,NaN,0.202039,NaN,NaN,NaN,NaN
2,3,3,Chadiza,2003,0.227219,0.217295,5,Eastern,56960.977318,1.662302e+06,...,0.281255,0.353488,NaN,NaN,NaN,0.127414,0.198846,NaN,NaN,NaN
3,4,4,Chadiza,2004,0.025194,0.084612,6,Eastern,56773.795452,1.871819e+06,...,0.227219,0.281255,0.353488,NaN,NaN,0.071589,0.126208,0.200209,NaN,NaN
4,5,5,Chadiza,2005,-0.712003,-0.763748,5,Eastern,56703.324923,7.047053e+05,...,0.025194,0.227219,0.281255,0.353488,NaN,-0.137126,0.071868,0.129584,0.164174,NaN

### Cumulative drought year effects

In [11]:
# sort values
plot_df = plot_df.sort_values(['district', 'year']).copy()

# shift
for lag in range(1, 6):
    plot_df[f'mean_spei_lag_{lag}'] = plot_df.groupby('district')['mean_spei'].shift(lag)
    
# create compounded SPEI lags
for k in range(2, 6):
    cols = [f'mean_spei_lag_{i}' for i in range(1, k + 1)]
    plot_df[f'mean_spei_cum{k}'] = plot_df[cols].mean(axis=1)

plot_df.head()

,Unnamed: 0.1,Unnamed: 0,district,year,mean_spei,median_spei,n_months,province,forest_cover_ha,loss_m2,...,z_spei_lag5,mean_spei_lag_1,mean_spei_lag_2,mean_spei_lag_3,mean_spei_lag_4,mean_spei_lag_5,mean_spei_cum2,mean_spei_cum3,mean_spei_cum4,mean_spei_cum5
0,1,1,Chadiza,2001,0.353488,0.303945,6,Eastern,57181.013721,5.136993e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,Chadiza,2002,0.281255,0.244052,6,Eastern,57127.207503,5.380622e+05,...,NaN,0.353488,NaN,NaN,NaN,NaN,0.353488,0.353488,0.353488,0.353488
2,3,3,Chadiza,2003,0.227219,0.217295,5,Eastern,56960.977318,1.662302e+06,...,NaN,0.281255,0.353488,NaN,NaN,NaN,0.317372,0.317372,0.317372,0.317372
3,4,4,Chadiza,2004,0.025194,0.084612,6,Eastern,56773.795452,1.871819e+06,...,NaN,0.227219,0.281255,0.353488,NaN,NaN,0.254237,0.287321,0.287321,0.287321
4,5,5,Chadiza,2005,-0.712003,-0.763748,5,Eastern,56703.324923,7.047053e+05,...,NaN,0.025194,0.227219,0.281255,0.353488,NaN,0.126207,0.177890,0.221789,0.221789

In [12]:
def compute_cum_corrs(group):
    results = {}
    y_col = "percent_loss_annual"

    for k in range(2, 6):
        x_col = f"mean_spei_cum{k}"

        if x_col in group:
            valid = group[[x_col, y_col]].dropna()

            if len(valid) >= 3:
                slope, intercept, r_value, p_value, std_err = linregress(
                    valid[x_col], valid[y_col]
                )
                results[f"corr_cum{k}"] = r_value
                results[f"pval_cum{k}"] = p_value
                results[f"slope_cum{k}"] = slope
                results[f"r2_cum{k}"] = r_value ** 2
            else:
                results[f"corr_cum{k}"] = None
                results[f"pval_cum{k}"] = None
                results[f"slope_cum{k}"] = None
                results[f"r2_cum{k}"] = None
        else:
            results[f"corr_cum{k}"] = None
            results[f"pval_cum{k}"] = None
            results[f"slope_cum{k}"] = None
            results[f"r2_cum{k}"] = None

    return pd.Series(results)

In [13]:
cum_corrs = (
    plot_df
    .groupby("district")[["mean_spei_cum2", "mean_spei_cum3",
                          "mean_spei_cum4", "mean_spei_cum5",
                          "percent_loss_annual"]]
    .apply(compute_cum_corrs)
    .reset_index()
)

In [14]:
for k in range(2, 6):
    corr_col = f"corr_cum{k}"
    pval_col = f"pval_cum{k}"
    slope_col = f"slope_cum{k}"
    r2_col = f"r2_cum{k}"

    significant = cum_corrs[cum_corrs[pval_col] < 0.05][
        ["district", corr_col, pval_col, slope_col, r2_col]
    ]

    print(f"\nSignificant correlations for cumulative {k}-year SPEI (p < 0.05):")
    print(significant.sort_values(by=corr_col, ascending=False).to_string(index=False))

Significant correlations for cumulative 2-year SPEI (p < 0.05):
district  corr_cum2  pval_cum2  slope_cum2  r2_cum2
Mpulungu   0.665938   0.001349    0.187563 0.443473
   Mbala   0.581133   0.007205    0.386467 0.337715
   Isoka   0.566116   0.009267    0.179915 0.320488
 Serenje  -0.459100   0.041726   -0.137052 0.210773
  Mumbwa  -0.461944   0.040316   -0.319268 0.213392
 Chavuma  -0.462726   0.039934   -0.504850 0.214116

Significant correlations for cumulative 3-year SPEI (p < 0.05):
district  corr_cum3  pval_cum3  slope_cum3  r2_cum3
Mpulungu   0.695077   0.000669    0.242704 0.483132
   Isoka   0.585073   0.006732    0.223141 0.342310
   Mbala   0.554915   0.011099    0.456312 0.307930
  Mumbwa  -0.450316   0.046324   -0.342354 0.202784
  Mkushi  -0.452923   0.044920   -0.289570 0.205139
  Lusaka  -0.466362   0.038198   -0.766164 0.217494
 Chavuma  -0.486873   0.029474   -0.550175 0.237046
 Serenje  -0.513019   0.020711   -0.162984 0.263188
Chibombo  -0.516753   0.019650   -0.723941 0.267033

Significant correlations for cumulative 4-year SPEI (p < 0.05):
district  corr_cum4  pval_cum4  slope_cum4  r2_cum4
Mpulungu   0.757876   0.000108    0.326244 0.574376
   Isoka   0.527307   0.016885    0.236448 0.278053
   Mbala   0.519255   0.018964    0.523844 0.269626
 Chavuma  -0.473648   0.034896   -0.551954 0.224342
  Mkushi  -0.488168   0.028981   -0.328862 0.238308
Chibombo  -0.490084   0.028263   -0.768838 0.240183
   Mansa  -0.513387   0.020604   -0.614583 0.263567
 Serenje  -0.525182   0.017415   -0.179754 0.275816
Chingola  -0.578159   0.007581   -0.684949 0.334267

Significant correlations for cumulative 5-year SPEI (p < 0.05):
     district  corr_cum5  pval_cum5  slope_cum5  r2_cum5
     Mpulungu   0.757234   0.000111    0.385678 0.573404
        Isoka   0.556245   0.010867    0.289442 0.309408
        Mbala   0.480496   0.031999    0.594555 0.230876
    Mporokoso   0.465181   0.038756    0.853785 0.216393
       Kasama  -0.456396   0.043102   -0.363867 0.208297
      Chavuma  -0.456724   0.042933   -0.553825 0.208597
      Luwingu  -0.474891   0.034355   -0.418734 0.225522
       Mwense  -0.492859   0.027249   -0.609184 0.242910
     Kawambwa  -0.494905   0.026519   -0.548536 0.244931
     Chinsali  -0.499346   0.024989   -0.356217 0.249347
Chililabombwe  -0.511300   0.021214   -1.016879 0.261428
      Serenje  -0.519183   0.018984   -0.195187 0.269551
       Mkushi  -0.523411   0.017867   -0.374380 0.273959
        Mansa  -0.589558   0.006224   -0.775724 0.347579
     Chingola  -0.693691   0.000693   -0.901346 0.481207